### ISSUE TITLE
Resolve a new Instance or a Singleton-Instance should support an Initialize behavior with Promise support

### ISSUE THREAD

**Issue by moellenbeck** [5minds/addict-ioc#38]
E.g. to create a Database singleton and start the connection a onNewInstance behavior with Promise support would make the application code more clear. The technical requirement have no influence to the application code.

```javascript
contrainer.register('some-db-key', SomeDatabase)
   .afterResolve((instance) => {
       return new Promise(resolve, reject) => {
         return instance.initialize();
       });
   })
   .singleton();
```

**Comment by ElRaptorus** [comment]
@moellenbeck @5ebastianMeier I think this has been implemented with the `InvocationContainer`, has it not?
