### ISSUE TITLE
Resolving a certain dependency-layout wrongfully results in Error

### ISSUE THREAD

**Issue by heikomat** [5minds/addict-ioc#41]
Lets say i have the classes `A`, `B` and `C`.

Now i register `C` as Dependency of `B`, and i register `B` AND `C` as Dependencies of `A`.
```
A
├── B
│   └── C
└── C
```

When trying to resolve this, Addict throws an error with the message `Circular dependency on key 'C' detected`. in line 300 in the container.js.

This is probably because when resolving the classes, Addict remembers a history of resolved names, so it can detect circular dependencies. When resolving `A`, it first resolves `B`. To resolve `B`, it resolves `C`. After that is done `B` is completely resolved, and to finish resolving `A`, it now just needs to resolve `C`. But because `C` was already resolved before through `B`, it's already in the resolve-history, and addict thinks it's circular, even if it's not, resulting in the previously mentioned error.

Marking `C` As singleton works around this issue.

**Comment by 5ebastianMeier** [comment]
This should now be fixed - this was a bug because the underlying case wasn't even a circular dependency.
