### ISSUE TITLE
update docs?

### ISSUE THREAD

**Issue by agalazis** [5minds/addict-ioc#45]
`The package exports a singleton container to be used all over your application.`
This is not a case. What's exported is not the singleton container but some classes.After checking the source I ended up doing something like this to make it work:
 
```
const {DependencyInjectionContainer} = require('addict-ioc');
 const container = new DependencyInjectionContainer()
 
container.setDefaults({
  isSingleton: false,
  wantsInjection: true,
  isLazy: false,
  bindFunctions: false,
  autoCreateMissingSubscribers: true
});
class SomeUserRepository {}
 
container.register('UserRepo', SomeUserRepository);
 
class SomeEmailService {}
 
container.register('EmailService', SomeEmailService);
 
class MyUserNotifier {
 
  constructor(userRepository, emailService) {
    this._userRepository = userRepository;
    this._emailService = emailService;
  }
}
 
container.register('UserNotifier', MyUserNotifier)
  .dependencies('UserRepo', 'EmailService');
 
const myUserNotifierInstance = container.resolve('UserNotifier');
```

**Comment by 5ebastianMeier** [comment]
@agalazis sorry you're absolutely right - this is something left over from the previous implementation that used the `commonjs` module system.

I'll update it later today.

To get you started, you need to do the following to get an instance of the container:

in commonjs:
```javascript
const DependencyInjectionContainer = require('addict-ioc').DependencyInjectionContainer;

const container = new DependencyInjectionContainer();
```

in es6:

```javascript
import {DependencyInjectionContainer} from 'addict-ioc';

const container = new DependencyInjectionContainer();
```

**Comment by 5ebastianMeier** [comment]
also: you don't need to set the default values if you don't want to customize the default values - I think the first example in the readme was a bit misleading there as that step is meant to be optional.

**Comment by 5ebastianMeier** [comment]
@agalazis I updated the readme - please have a look if this is explained correctly now.

If you have any other issues, please don't hesitate to open an issue.
Thanks for your support!

**Comment by 5ebastianMeier** [comment]
#46
