### ISSUE TITLE
some typings aren't working out

### ISSUE THREAD

**Issue by heikomat** [5minds/addict-ioc#52]
when creating an invocationContainer, i'm able to give it the following setting:
```
{
  defaults: {
    conventionCalls: ['initialize'],
  },
}
```

This works technically, but typescript says this is not valid:
```
[ts]
Argument of type '{ defaults: { conventionCalls: string[]; }; }' is not assignable to parameter of type 'IContainerSettings'.
  Property 'containerRegistrationKey' is missing in type '{ defaults: { conventionCalls: string[]; }; }'.
(property) defaults: {
    conventionCalls: string[];
}
```

**Comment by 5ebastianMeier** [comment]
@heikomat thanks for mentioning - I think I can make more of those properties optional since the default settings take care of it

**Comment by 5ebastianMeier** [comment]
should be fixed by https://github.com/5minds/addict-ioc/commit/8a7de1d274f31fa503a3362c34d47e5a3ce4715a
