### ISSUE TITLE
Documentation should be updated

### ISSUE THREAD

**Issue by cosminghitea** [5minds/addict-ioc#57]
Hi I tried to use the documentation with the new version 2.3.4 and seem like the DependencyInjectionContainer member don't exit just in older version should that be change in Container or something?

**Comment by 5ebastianMeier** [comment]
I'm on it. The documentation does not yet reflect addict-ioc@2 - it's still on version 1.
In addict-ioc@2 there are 2 container types you can use:
* Container (regular IoC container)
* InvocationContainer (regular IoC container + auto-invoked lifecycle methods)
