### ISSUE TITLE
Dependencies of Registrations tagged with ExtensionDiscoveryTag do not support singleton behavior

### ISSUE THREAD

**Issue by stheuer** [5minds/addict-ioc#71]
#### Describe your issue

When bootsrapping an applicatiom with the help of npm packages @essential-projects/bootstrapper/  @essential-projects/bootstrapper_node and @essential-projects/core_contracts a type  may instanciate and initialize twice though marked as singelton.

This is if two components which are tagged as ExtensionDiscoveryTag depend an the singleton registration.

#### How can others reproduce the issue?
Run following Programm below (you need to setup a folder config/development next to the index.js file)

.... and you get logs

```
>node index.js
constructor A
constructor A
initialize A
initialize A

```

index.js

```
'use strict';
const InvocationContainer = require('addict-ioc').InvocationContainer;

const ExtensionDiscoveryTag = require('@essential-projects/core_contracts').ExtensionDiscoveryTag;
const dependencies = [
  '@essential-projects/bootstrapper/',
  '@essential-projects/bootstrapper_node/',
];

const iocModules = dependencies.map((moduleName) => {
  return require(`${moduleName}/ioc_module`); // eslint-disable-line global-require
});

class A {
  constructor() {
    console.log('constructor A');
  }
  initialize() {
    console.log('initialize A');
  }
}

class B {}

class  C {}


async function start() {
  
  const container = new InvocationContainer({
    defaults: {
      conventionCalls: ['initialize'],
    },
  });

  for (const iocModule of iocModules) {
    iocModule.registerInContainer(container);
  }

  try {
    const bootstrapper = await container.resolveAsync('AppBootstrapper');

    container.register('A', A)
      .singleton();

    container.register('B', B)
      .dependencies('A')
      .tags(ExtensionDiscoveryTag);

    container.register('C', C)
      .dependencies('A')
      .tags(ExtensionDiscoveryTag);

    await bootstrapper.start();
  } catch (error) {
    console.log(error);
    process.exit(1);
}

}

start();

```

#### What's your setup

- OS ManjaroLinux 18.0.2:
- Node (`node --version`): v8.11.3
- NPM (`npm --version`): 5.6.0

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@stheuer  Please refrain from using `@essential-projects/core_contracts`, that package has been depcerated for over half a year and is no longer maintained.

All contracts you should need for bootstrapping are located in `@essential-projects/bootstrapper_contracts` and `@essential-projects/http_contracts`.

As for the other packages, which versions are you using?

**Comment by ElRaptorus** [comment]
>     * OS ManjaroLinux 18.0.2:

Very cool, btw. 😎

**Comment by stheuer** [comment]
Hi I updated dependencies so my package.json looks like 
```

   :
  "dependencies": {
    "@essential-projects/bootstrapper": "^3.3.0",
    "@essential-projects/bootstrapper_contracts": "^1.3.0",
    "@essential-projects/bootstrapper_node": "^3.2.4",
    "addict-ioc": "^2.5.4"
  }
  :

```

**Comment by ElRaptorus** [comment]
@stheuer Ok, good to know. We'll look into this.

**Comment by SimonSchneiderHSM** [comment]
@ElRaptorus 
We still have an open bug ticket due to this.
Is there any progress? Any plans to fix this.

**Comment by 5ebastianMeier** [comment]
@SimonSchneiderHSM the issue was identified and resolved in https://github.com/essential-projects/bootstrapper/pull/7.
